name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.bonfire_test_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build --web-renderer=canvaskit
      - run: |
          cd build/web
          git init
          # type configurations: your user.email and user.name followed lines 
          # git config --global user.email your_email 
          # git config --global user.name your_name 
          git config --global user.email kristian.tuusjarvi@gmail.com
          git config --global user.name thevikke
          git status
          # change this remote url for examle your remote url is https://github.com/thevikke/bonfire_test.git then the following:
          git remote add origin https://${{secrets.bonfire_test_secret}}@github.com/thevikke/bonfire_test.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
